# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "parallel"
batch_size_run: 7

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "metaq_v5_learner"
double_q: True
mixer: "metaq_v5_heter" 
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
agent: "ant_demo"

name: "ant_metaq_2s3z"

# hyperparameter
model_dim: 16
num_heads: 2
ffn_dim: 64
dropout: 0.0

# transformer mix
metaq_transformer_model_dim: 32
metaq_transformer_ffn_dim: 128
metaq_transformer_n_heads: 4
metaq_transformer_dropout: 0.0
metaq_final_layer_dim: 32

#v1.1
fc_c_dim: 64

# v2
fc_mul_dim: 32
fc_add_dim: 32
last_action_extend_dim: 14
agent_id_dim: 13


# log
use_tensorboard: True # Log results to tensorboard
save_model: True # Save the models to disk
t_max: 8050000
