# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "parallel"
batch_size_run: 7

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer:  "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
agent: "updet"

name: "updet_1s2z_2s3z"

# hyperparameter
model_dim: 32
num_heads: 3
ffn_dim: 64
dropout: 0.0
last_action_dim: 15



# log
use_tensorboard: True # Log results to tensorboard
save_model: True # Save the models to disk
t_max: 7005000
save_model_interval: 200000

#checkpoint_path: "/home/q/桌面/test/PIT_TF/results/models/updet_2s3z__2021-02-07_12-49-05/"
#checkpoint_path: "/home/q/桌面/test/PIT_TF/results/models/updet_2s3z__2021-02-07_12-49-07/"
#checkpoint_path: "/home/q/桌面/test/PIT_TF/results/models/updet_2s3z__2021-02-08_02-32-41/"

#checkpoint_path: "/home/q/code/PIT_TF/results/models/updet_1s2z__2021-05-17_09-39-07/"
#checkpoint_path: "/home/q/code/PIT_TF/results/models/updet_1s2z__2021-05-17_09-39-10/"
#checkpoint_path: "/home/q/code/PIT_TF/results/models/updet_1s2z__2021-05-17_09-39-14/"
#checkpoint_path: "/home/q/code/PIT_TF/results/models/updet_1s2z__2021-05-17_09-39-19/"

#checkpoint_path: "/home/q/code/PIT_TF/results/models/updet_1s2z_2s3z__2021-05-17_22-04-34/"
#checkpoint_path: "/home/q/code/PIT_TF/results/models/updet_1s2z_2s3z__2021-05-17_22-04-39/"
#checkpoint_path: "/home/q/code/PIT_TF/results/models/updet_1s2z_2s3z__2021-05-18_08-59-57/"
checkpoint_path: "/home/q/code/PIT_TF/results/models/updet_1s2z_2s3z__2021-05-18_09-00-00/"